name: Scale_down
on:
#     schedule:
#        - cron: '30 15 * * 1-5'
   workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          sudo apt-get install awscli
          aws --version
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Uodate kube-config
        run: |
         aws  eks --region ap-south-1  update-kubeconfig --name cloudifytests
         eksctl scale nodegroup --cluster=cloudifytests --nodes=1 --name=cloudbrowser  --nodes-min=0  --nodes-max=1
         eksctl scale nodegroup --cluster=cloudifytests --nodes=1 --name=userapp  --nodes-min=0  --nodes-max=1
